# Generated by Django 3.2.6 on 2021-08-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('nickname', models.CharField(max_length=45)),
                ('image_url', models.URLField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
