# Generated by Django 3.2.6 on 2021-08-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('number', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=1)),
                ('hours', models.CharField(max_length=45)),
                ('info', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'cafes',
            },
        ),
    ]
