# Generated by Django 3.2.6 on 2021-08-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
