# Generated by Django 3.2.6 on 2021-08-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_auto_20210802_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='stars',
        ),
    ]
