# Generated by Django 3.2.6 on 2021-08-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_remove_cafe_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='image_url',
            new_name='background_image_url',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='info',
            new_name='information',
        ),
        migrations.AddField(
            model_name='cafe',
            name='poster_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
