# Generated by Django 3.2.6 on 2021-08-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starrating',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
